"""由已验证计划生成确定性采集脚本，并执行、比对结果。

collector.py 是「受信任模板 + 已验证计划」的组合产物，不是模型生成的代码，
也不由模型自由编写；本模块不调用 LLM。
"""

import asyncio
import json
from pathlib import Path
import subprocess
import sys

from .contracts import Observation, SENSITIVE, has_sensitive_keys, local_origin


_TEMPLATE = '''#!/usr/bin/env python3
"""Deterministic page-number collector generated by Web Data Agent.

Fixed template plus a validated plan; this file is not model-generated code.
Supports literal loopback HTTP, GET, page-number pagination, up to 10 pages.
Run: python collector.py [--url URL] [--max-pages N] [--output PATH]
"""
import argparse
import json
import math
import sys
import urllib.error
import urllib.parse
import urllib.request

CONFIG = __CONFIG__


class RedirectBlocked(Exception):
    pass


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *args, **kwargs):
        raise RedirectBlocked('redirect_not_followed')


def _loopback(url):
    parts = urllib.parse.urlsplit(url)
    if parts.scheme != 'http' or parts.hostname not in ('127.0.0.1', '::1'):
        raise ValueError('only_literal_loopback_http_supported')
    if parts.username or parts.password or parts.fragment:
        raise ValueError('only_literal_loopback_http_supported')
    return url


def _pointer(data, path):
    if path == '':
        return data
    if not path.startswith('/'):
        raise ValueError('invalid_json_pointer')
    for part in path[1:].split('/'):
        key = part.replace('~1', '/').replace('~0', '~')
        if isinstance(data, list):
            if not key.isdigit() or (len(key) > 1 and key[0] == '0'):
                raise ValueError('invalid_array_index')
            if int(key) >= len(data):
                raise ValueError('pointer_not_found')
            data = data[int(key)]
        elif isinstance(data, dict):
            if key not in data:
                raise ValueError('pointer_not_found')
            data = data[key]
        else:
            raise ValueError('pointer_not_found')
    return data


def _fetch(opener, url, params):
    query = urllib.parse.urlencode(params)
    request = urllib.request.Request(url + ('?' + query if query else ''),
                                     headers={'Accept': 'application/json'})
    try:
        with opener.open(request, timeout=10) as response:
            if not 200 <= response.getcode() < 300:
                raise RuntimeError('http_status_%s' % response.getcode())
            declared = response.headers.get('Content-Length')
            if declared is not None and int(declared) > 256 * 1024:
                raise RuntimeError('response_too_large')
            raw = response.read(256 * 1024 + 1)
    except urllib.error.HTTPError as error:
        raise RuntimeError('http_status_%s' % error.code) from None
    except urllib.error.URLError:
        raise RuntimeError('network_error') from None
    if len(raw) > 256 * 1024:
        raise RuntimeError('response_too_large')
    body = json.loads(raw.decode('utf-8'))
    if not isinstance(body, (dict, list)):
        raise RuntimeError('expected_object_or_list')
    return body


def collect(config):
    opener = urllib.request.build_opener(_NoRedirect)
    base_query = dict(config['query'])
    items = []
    seen = set()
    sample_types = None
    expected_total = None
    pages = 0
    for page in range(1, config['max_pages'] + 1):
        pages = page
        query = dict(base_query)
        query[config['page_parameter']] = str(page)
        body = _fetch(opener, config['url'], query)
        rows = _pointer(body, config['items_pointer'])
        if not isinstance(rows, list):
            raise RuntimeError('items_not_list')
        if sample_types is None:
            if not rows:
                raise RuntimeError('no_list_sample')
            sample_types = {name: type(_pointer(rows[0], path)).__name__
                            for name, path in config['fields'].items()}
        if config['total_pointer'] is not None:
            total = _pointer(body, config['total_pointer'])
            if type(total) is not int or total < 0:
                raise RuntimeError('invalid_total')
            if expected_total is not None and total != expected_total:
                raise RuntimeError('total_changed')
            expected_total = total
        for row in rows:
            record = {name: _pointer(row, path) for name, path in config['fields'].items()}
            for name, value in record.items():
                if type(value) not in (int, float, str, bool):
                    raise RuntimeError('field_type_invalid')
                if type(value).__name__ != sample_types[name]:
                    raise RuntimeError('field_type_changed')
                if isinstance(value, float) and not math.isfinite(value):
                    raise RuntimeError('non_finite_number')
            key = record[config['unique_key']]
            if type(key) not in (int, str) or key == '':
                raise RuntimeError('invalid_unique_key')
            if key in seen:
                raise RuntimeError('duplicate_id')
            seen.add(key)
            items.append(record)
        if expected_total is not None and len(items) > expected_total:
            raise RuntimeError('too_many_items')
        if config['has_next_pointer'] is not None:
            more = _pointer(body, config['has_next_pointer'])
            if type(more) is not bool:
                raise RuntimeError('invalid_has_next')
        else:
            more = bool(rows) and (expected_total is None or len(items) < expected_total)
        if more and not rows:
            raise RuntimeError('empty_page_with_next')
        if not more:
            if expected_total is not None and len(items) != expected_total:
                raise RuntimeError('incomplete_items')
            return {'items': items, 'pages': pages, 'expected_total': expected_total,
                    'completeness': 'complete' if expected_total is not None else 'stop_condition_only'}
    return {'items': items, 'pages': pages, 'expected_total': expected_total, 'completeness': 'partial'}


def main():
    parser = argparse.ArgumentParser(description='Deterministic loopback page-number collector.')
    parser.add_argument('--url', default=None, help='覆盖脚本内置的本机接口地址')
    parser.add_argument('--max-pages', type=int, default=None, help='最多页数，1～10')
    parser.add_argument('--output', default='collector_result.json', help='结果 JSON 输出路径')
    args = parser.parse_args()
    config = dict(CONFIG)
    if args.url is not None:
        config['url'] = args.url
    if args.max_pages is not None:
        config['max_pages'] = args.max_pages
    try:
        _loopback(config['url'])
        if not 1 <= config['max_pages'] <= 10:
            raise ValueError('max_pages_out_of_range')
        result = collect(config)
    except Exception as error:  # 独立脚本：把任何失败转为稳定退出码与短摘要
        print(json.dumps({'status': 'failed', 'error': type(error).__name__}, ensure_ascii=False))
        return 1
    with open(args.output, 'w', encoding='utf-8') as handle:
        json.dump(result, handle, ensure_ascii=False, indent=2)
        handle.write('\\n')
    print(json.dumps({'status': 'succeeded', 'count': len(result['items']), 'pages': result['pages'],
                      'completeness': result['completeness'], 'output': args.output}, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    sys.exit(main())
'''


# POST JSON 模板与 GET 模板相互独立，POST 走单独路径。
_POST_TEMPLATE = '''#!/usr/bin/env python3
"""Deterministic POST JSON page-number collector generated by Web Data Agent.

Fixed template plus a validated plan; this file is not model-generated code.
Supports literal loopback HTTP, POST application/json, page-number pagination,
up to 10 pages. Only the page field of the JSON body is mutated.
Run: python collector.py [--url URL] [--max-pages N] [--output PATH]
"""
import argparse
import json
import math
import sys
import urllib.error
import urllib.parse
import urllib.request

CONFIG = __CONFIG__


class RedirectBlocked(Exception):
    pass


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *args, **kwargs):
        raise RedirectBlocked('redirect_not_followed')


def _loopback(url):
    parts = urllib.parse.urlsplit(url)
    if parts.scheme != 'http' or parts.hostname not in ('127.0.0.1', '::1'):
        raise ValueError('only_literal_loopback_http_supported')
    if parts.username or parts.password or parts.fragment:
        raise ValueError('only_literal_loopback_http_supported')
    return url


def _pointer(data, path):
    if path == '':
        return data
    if not path.startswith('/'):
        raise ValueError('invalid_json_pointer')
    for part in path[1:].split('/'):
        key = part.replace('~1', '/').replace('~0', '~')
        if isinstance(data, list):
            if not key.isdigit() or (len(key) > 1 and key[0] == '0'):
                raise ValueError('invalid_array_index')
            if int(key) >= len(data):
                raise ValueError('pointer_not_found')
            data = data[int(key)]
        elif isinstance(data, dict):
            if key not in data:
                raise ValueError('pointer_not_found')
            data = data[key]
        else:
            raise ValueError('pointer_not_found')
    return data


def _fetch(opener, url, params, payload):
    # 与内部执行器一致：query 来自独立的观察元数据，不修改任何成员。
    parts = urllib.parse.urlsplit(url)
    url = urllib.parse.urlunsplit(parts._replace(query=urllib.parse.urlencode(params)))
    request = urllib.request.Request(url, data=json.dumps(payload).encode('utf-8'), method='POST',
                                     headers={'Accept': 'application/json',
                                              'Content-Type': 'application/json'})
    try:
        with opener.open(request, timeout=10) as response:
            if not 200 <= response.getcode() < 300:
                raise RuntimeError('http_status_%s' % response.getcode())
            declared = response.headers.get('Content-Length')
            if declared is not None and int(declared) > 256 * 1024:
                raise RuntimeError('response_too_large')
            raw = response.read(256 * 1024 + 1)
    except urllib.error.HTTPError as error:
        raise RuntimeError('http_status_%s' % error.code) from None
    except urllib.error.URLError:
        raise RuntimeError('network_error') from None
    if len(raw) > 256 * 1024:
        raise RuntimeError('response_too_large')
    body = json.loads(raw.decode('utf-8'))
    if not isinstance(body, (dict, list)):
        raise RuntimeError('expected_object_or_list')
    return body


def collect(config):
    opener = urllib.request.build_opener(_NoRedirect)
    base_body = dict(config['request_body'])
    items = []
    seen = set()
    sample_types = None
    expected_total = None
    pages = 0
    for page in range(1, config['max_pages'] + 1):
        pages = page
        payload = dict(base_body)
        # 只修改页码成员；其余请求体成员与观察到的样本保持逐字一致。
        payload[config['page_parameter']] = page
        body = _fetch(opener, config['url'], config['query'], payload)
        rows = _pointer(body, config['items_pointer'])
        if not isinstance(rows, list):
            raise RuntimeError('items_not_list')
        if sample_types is None:
            if not rows:
                raise RuntimeError('no_list_sample')
            sample_types = {name: type(_pointer(rows[0], path)).__name__
                            for name, path in config['fields'].items()}
        if config['total_pointer'] is not None:
            total = _pointer(body, config['total_pointer'])
            if type(total) is not int or total < 0:
                raise RuntimeError('invalid_total')
            if expected_total is not None and total != expected_total:
                raise RuntimeError('total_changed')
            expected_total = total
        for row in rows:
            record = {name: _pointer(row, path) for name, path in config['fields'].items()}
            for name, value in record.items():
                if type(value) not in (int, float, str, bool):
                    raise RuntimeError('field_type_invalid')
                if type(value).__name__ != sample_types[name]:
                    raise RuntimeError('field_type_changed')
                if isinstance(value, float) and not math.isfinite(value):
                    raise RuntimeError('non_finite_number')
            key = record[config['unique_key']]
            if type(key) not in (int, str) or key == '':
                raise RuntimeError('invalid_unique_key')
            if key in seen:
                raise RuntimeError('duplicate_id')
            seen.add(key)
            items.append(record)
        if expected_total is not None and len(items) > expected_total:
            raise RuntimeError('too_many_items')
        if config['has_next_pointer'] is not None:
            more = _pointer(body, config['has_next_pointer'])
            if type(more) is not bool:
                raise RuntimeError('invalid_has_next')
        else:
            more = bool(rows) and (expected_total is None or len(items) < expected_total)
        if more and not rows:
            raise RuntimeError('empty_page_with_next')
        if not more:
            if expected_total is not None and len(items) != expected_total:
                raise RuntimeError('incomplete_items')
            return {'items': items, 'pages': pages, 'expected_total': expected_total,
                    'completeness': 'complete' if expected_total is not None else 'stop_condition_only'}
    return {'items': items, 'pages': pages, 'expected_total': expected_total, 'completeness': 'partial'}


def main():
    parser = argparse.ArgumentParser(description='Deterministic loopback POST JSON page-number collector.')
    parser.add_argument('--url', default=None, help='覆盖脚本内置的本机接口地址')
    parser.add_argument('--max-pages', type=int, default=None, help='最多页数，1～10')
    parser.add_argument('--output', default='collector_result.json', help='结果 JSON 输出路径')
    args = parser.parse_args()
    config = dict(CONFIG)
    if args.url is not None:
        config['url'] = args.url
    if args.max_pages is not None:
        config['max_pages'] = args.max_pages
    try:
        _loopback(config['url'])
        if not 1 <= config['max_pages'] <= 10:
            raise ValueError('max_pages_out_of_range')
        result = collect(config)
    except Exception as error:  # 独立脚本：把任何失败转为稳定退出码与短摘要
        print(json.dumps({'status': 'failed', 'error': type(error).__name__}, ensure_ascii=False))
        return 1
    with open(args.output, 'w', encoding='utf-8') as handle:
        json.dump(result, handle, ensure_ascii=False, indent=2)
        handle.write('\\n')
    print(json.dumps({'status': 'succeeded', 'count': len(result['items']), 'pages': result['pages'],
                      'completeness': result['completeness'], 'output': args.output}, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    sys.exit(main())
'''


def _write_json(path: Path, value):
    temporary = path.with_suffix(path.suffix + '.tmp')
    temporary.write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + '\n', encoding='utf-8')
    temporary.replace(path)


def _validate_export_inputs(plan, record, max_pages):
    """导出前复核：与执行器相同的 loopback / 敏感字段 / 分页约束。"""
    if not isinstance(max_pages, int) or not 1 <= max_pages <= 10:
        raise ValueError('max_pages_out_of_range')
    if not isinstance(record, Observation) or record.request_id != plan.request_id:
        raise ValueError('unknown_request_id')
    local_origin(record.url)
    if any(SENSITIVE.search(key) for key in record.query):
        raise ValueError('sensitive_request_not_supported')
    if plan.pagination_location == 'json_body':
        # POST：页码是请求体顶层整数成员，只允许回放被观察到的 body。
        if record.method != 'POST':
            raise ValueError('page_location_mismatch')
        body = record.request_body if isinstance(record.request_body, dict) else {}
        if plan.page_parameter not in body or type(body[plan.page_parameter]) is not int:
            raise ValueError('unobserved_page_parameter')
        if has_sensitive_keys(record.request_body):
            raise ValueError('sensitive_request_not_supported')
    else:
        if record.method != 'GET':
            raise ValueError('page_location_mismatch')
        if plan.page_parameter not in record.query or not record.query[plan.page_parameter].isdecimal():
            raise ValueError('unobserved_page_parameter')
    if plan.unique_key not in plan.fields:
        raise ValueError('unique_key_not_in_fields')
    for name, path in plan.fields.items():
        if not path.startswith('/') or SENSITIVE.search(name) or SENSITIVE.search(path):
            raise ValueError('invalid_or_sensitive_field')


def build_collector_source(plan, record, max_pages: int) -> str:
    """把已验证计划固化为确定性脚本源码；相同输入产出相同字节。"""
    _validate_export_inputs(plan, record, max_pages)
    post = plan.pagination_location == 'json_body'
    # query 始终来自观察元数据；POST 额外保存请求体作为分页载体。
    request_carrier = ({'request_body': dict(record.request_body), 'query': dict(record.query)}
                       if post else {'query': dict(record.query)})
    config = {
        'url': record.url,
        **request_carrier,
        'items_pointer': plan.items_pointer,
        'fields': dict(plan.fields),
        'unique_key': plan.unique_key,
        'page_parameter': plan.page_parameter,
        'has_next_pointer': plan.has_next_pointer,
        'total_pointer': plan.total_pointer,
        'max_pages': max_pages,
    }
    template = _POST_TEMPLATE if post else _TEMPLATE
    # JSON 是数据而非 Python 表达式；repr 将文本安全封装为 Python 字符串。
    serialized = json.dumps(config, ensure_ascii=False, indent=2, allow_nan=False)
    return template.replace('__CONFIG__', f'json.loads({serialized!r})')


def write_collector_artifact(folder, source: str) -> Path:
    """原子写入 collector.py，避免半写入文件被登记。"""
    folder = Path(folder)
    path = folder / 'collector.py'
    temporary = path.with_suffix('.py.tmp')
    temporary.write_text(source, encoding='utf-8')
    temporary.replace(path)
    return path


async def run_exported_collector(folder, timeout_seconds: float = 30) -> dict:
    """用真实 Python 进程执行 collector.py，读取其 JSON 产物。失败不抛异常。"""
    def invoke():
        return subprocess.run([sys.executable, 'collector.py', '--output', 'collector_result.json'],
                              cwd=str(folder), capture_output=True, text=True, timeout=timeout_seconds)
    completed = await asyncio.to_thread(invoke)
    path = Path(folder) / 'collector_result.json'
    payload = None
    if path.is_file():
        try:
            payload = json.loads(path.read_text(encoding='utf-8'))
        except ValueError:
            payload = None
    return {'exit_code': completed.returncode,
            'stdout': (completed.stdout or '').strip()[:2000],
            'stderr': (completed.stderr or '').strip()[:2000],
            'result': payload,
            'success': completed.returncode == 0 and isinstance(payload, dict)}


def _ordered(records, unique_key):
    return sorted(records, key=lambda row: (type(row.get(unique_key)).__name__, str(row.get(unique_key))))


def compare_exported_result(internal, exported, unique_key: str) -> dict:
    """比对内部执行结果与导出脚本结果；顺序不作为约束。"""
    if not isinstance(exported, dict):
        return {'matches': False, 'reason': 'collector_result_missing'}
    internal_items = internal.get('items', [])
    exported_items = exported.get('items', [])

    def shape(records):
        if not records:
            return [], {}
        names = sorted(records[0])
        return names, {name: type(records[0][name]).__name__ for name in names}

    internal_names, internal_types = shape(internal_items)
    exported_names, exported_types = shape(exported_items)
    internal_keys = [row.get(unique_key) for row in internal_items]
    exported_keys = [row.get(unique_key) for row in exported_items]
    checks = {
        'pages': internal.get('pages') == exported.get('pages'),
        'completeness': internal.get('completeness') == exported.get('completeness'),
        'expected_total': internal.get('expected_total') == exported.get('expected_total'),
        'record_count': len(internal_items) == len(exported_items),
        'field_names': internal_names == exported_names,
        'field_types': internal_types == exported_types,
        'unique_keys': len(set(internal_keys)) == len(internal_keys) and len(set(exported_keys)) == len(exported_keys),
        'records': _ordered(internal_items, unique_key) == _ordered(exported_items, unique_key),
    }
    return {'matches': all(checks.values()), 'checks': checks,
            'internal': {'count': len(internal_items), 'pages': internal.get('pages'),
                         'completeness': internal.get('completeness')},
            'exported': {'count': len(exported_items), 'pages': exported.get('pages'),
                         'completeness': exported.get('completeness')}}


async def export_collector(folder, plan, record, internal, max_pages: int) -> dict:
    """生成、执行并比对 collector.py，写入产物，返回报告片段。"""
    folder = Path(folder)
    write_collector_artifact(folder, build_collector_source(plan, record, max_pages))
    outcome = await run_exported_collector(folder)
    verification = compare_exported_result(internal, outcome['result'], plan.unique_key)
    verification['collector_exit_code'] = outcome['exit_code']
    verification['collector_stdout'] = outcome['stdout']
    verification['collector_stderr'] = outcome['stderr']
    _write_json(folder / 'collector_verification.json', verification)
    return {'collector_exported': True,
            'collector_execution_success': bool(outcome['success']),
            'collector_matches_internal_result': bool(verification.get('matches'))}
